# Generated by Django 3.1.2 on 2020-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('median_price', models.FloatField()),
                ('description', models.CharField(max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('covid_friendly', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
